server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
      url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding-utr-8&useSSL=false
      username: root
      password: root

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.zhubing.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/

